# Generated by Django 4.2.4 on 2023-08-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='repository_url',
        ),
        migrations.AddField(
            model_name='project',
            name='deploy_url',
            field=models.URLField(blank=True),
        ),
    ]
